
import LenisProvider from "./components/LenisProvider";
import {Inter,JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const inter = Inter({
  subsets:["latin"],
  variable:"--font-inter",
  display:"swap",
})

export const jetbrainsMono = JetBrains_Mono({
  subsets:["latin"],
  variable:"--font-jetbrains-mono",
  display:"swap"
})


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
         <LenisProvider>
              {children}
         </LenisProvider>
        </body>
    </html>
  );
}
